# Generated by Django 5.2.7 on 2025-10-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('feeid', models.AutoField(db_column='feeid', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='amount', decimal_places=2, max_digits=10, null=True)),
                ('duedate', models.DateField(blank=True, db_column='duedate', null=True)),
                ('status', models.CharField(blank=True, db_column='status', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fees',
                'db_table': 'fee',
                'ordering': ['-duedate'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.fee',),
        ),
    ]
