# Generated by Django 5.2.7 on 2025-10-22 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Fees', 'Fees'), ('Hostel', 'Hostel'), ('Fests', 'Fests'), ('Clubs/Chapters', 'Clubs/Chapters')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_record', to='payments.fee')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
            },
        ),
    ]
