# Generated by Django 5.2.7 on 2025-10-14 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('allocationid', models.AutoField(db_column='allocationid', primary_key=True, serialize=False)),
                ('date_of_allocation', models.DateField(blank=True, db_column='date_of_allocation', null=True)),
            ],
            options={
                'verbose_name': 'Room Allocation',
                'verbose_name_plural': 'Room Allocations',
                'db_table': 'allocation',
                'ordering': ['-date_of_allocation'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.AutoField(db_column='studentid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('gender', models.CharField(blank=True, db_column='gender', max_length=10, null=True)),
                ('department', models.CharField(blank=True, db_column='department', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin/Warden'), ('student', 'Student'), ('staff', 'Staff')], default='student', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
    ]
