# Generated by Django 5.2.7 on 2025-10-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='hostel_mess',
            field=models.CharField(blank=True, choices=[('Buddies & Bites', 'Buddies & Bites'), ("Eat n' Chill", "Eat n' Chill"), ('The Late Plate', 'The Late Plate')], max_length=50, null=True),
        ),
    ]
