# Generated by Django 5.2.7 on 2025-10-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostelid', models.AutoField(db_column='hostelid', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True)),
                ('location', models.CharField(blank=True, db_column='location', max_length=100, null=True)),
                ('totalrooms', models.IntegerField(blank=True, db_column='totalrooms', null=True)),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
                'db_table': 'hostel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomid', models.AutoField(db_column='roomid', primary_key=True, serialize=False)),
                ('roomnumber', models.CharField(blank=True, db_column='roomnumber', max_length=10, null=True)),
                ('capacity', models.IntegerField(blank=True, db_column='capacity', null=True)),
                ('type', models.CharField(blank=True, db_column='type', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'room',
                'ordering': ['hostelid', 'roomnumber'],
                'managed': False,
            },
        ),
    ]
