# Generated by Django 5.2.7 on 2025-10-15 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complaint',
            table='complaint',
        ),
    ]
